api_platform:
    title: 'API Platform Template (with Symfony)'
    version: '1.0.0'
    openapi:
        contact:
            name: 'Alexander Serbe'
            email: 'codiersklave@yahoo.de'
        license:
            name: 'MIT License'
            url: 'https://mit-license.org/'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
        xml:
            mime_types:
                - application/xml
                - text/xml
